#!/usr/bin/with-contenv bash
# vim: ft=bash
# shellcheck shell=bash
# ==============================================================================
# Start OpenThread BorderRouter web interface
# ==============================================================================
# shellcheck source=./openthread_border_router/rootfs/etc/s6-overlay/scripts/otbr-agent-common
. /etc/s6-overlay/scripts/otbr-agent-common

if [ x"${OTBR_WEB:-1}" = x"0" ]; then
    echo "INFO: Skipping otbr-web, disabled..."
    exec s6-pause
fi

echo "INFO: Starting otbr-web..."

otbr_web_args=(
    "-I" "wpan0"
    "-d$(otbr_log_level_to_int)" "-s"
    "-p" "${OTBR_WEB_PORT:-8080}"
    "-a" "${OTBR_WEB_INTERFACE:-::}"
)

exec stdbuf -oL /usr/sbin/otbr-web "${otbr_web_args[@]}"
